Revert "✨ Verify Homebrew attestations at installation"
This reverts commit 8dad8cf64c5df8aca72a5dc187d9a3f6fde2dabc
because upgrade fails:

  ==> Verifying attestation for ca-certificates
  Error: The bottle for ca-certificates could not be verified.

  This typically indicates a missing GitHub API token, which you
  can resolve either by setting `HOMEBREW_GITHUB_API_TOKEN` or
  by running:

    gh auth login